config/routes.rb
SampleApp::Application.routes.draw do

  root :to =>             "static_pages#home"

  get 'home' =>           "static_pages#home"

  get 'help' =>           "static_pages#help"
  get 'about' =>          "static_pages#about"
  get 'contact' =>        "static_pages#contact"
  get "signup" =>         "users#new"

  get "login" =>          "sessions#new"              # name: login_path      action: new
  post "login" =>         "sessions#create"           # name: login_path      action: create
  delete "logout" =>      "sessions#destroy"          # name: logout_path     action: destroy

  resources :users
  resources :bears

end

app/models/bear.rb
class Bear < ActiveRecord::Base
  attr_accessible :age, :home, :name, :password_digest, :type
end

app/models/birthday.rb
class Birthday < ActiveRecord::Base
	belongs_to :student
  attr_accessible :day, :month, :year
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_and_belongs_to_many :students
  attr_accessible :code, :topic
end

app/models/course_membership.rb
class CourseMembership < ActiveRecord::Base
  attr_accessible :course_ids, :student_ids
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_and_belongs_to_many :courses
  has_one :birthday
  attr_accessible :age, :name
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible 	:email, :name, :password, :password_confirmation, :poo

  VALID_EMAIL_REGEX = /\A([^@\s\.]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  # generally don't do this
  before_save { self.email = email.downcase }

  validates :name, 	presence: 	true,
  									length: 		{ maximum: 50 }
  validates :email, presence: 	true,
  									length: 		{ maximum: 255 },
     								format: 		{ with: VALID_EMAIL_REGEX, message: "valid email required" },
     								uniqueness: { case_sensitive: false }

  validates :password, 					    length: { minimum: 6 },
   																	presence: true,
   																	format: { with: /\A[^ ]*\z/i }
  validates :password_confirmation, length: { minimum: 6 },
  																	presence: true,
  																	format: { with: /\A[^ ]*\z/i }

  has_secure_password

  # 
  # @param string {String} to be hashed
  # 
  def User.digest string

    cost = 20
    # ActiveModel::SecurePassword.min cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create string, cost: cost
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	include SessionsHelper

end

app/controllers/bears_controller.rb
class BearsController < ApplicationController
  # GET /bears
  # GET /bears.json
  def index
    @bears = Bear.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bears }
    end
  end

  # GET /bears/1
  # GET /bears/1.json
  def show
    @bear = Bear.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bear }
    end
  end

  # GET /bears/new
  # GET /bears/new.json
  def new
    @bear = Bear.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bear }
    end
  end

  # GET /bears/1/edit
  def edit
    @bear = Bear.find(params[:id])
  end

  # POST /bears
  # POST /bears.json
  def create
    @bear = Bear.new(params[:bear])

    respond_to do |format|
      if @bear.save
        format.html { redirect_to @bear, notice: 'Bear was successfully created.' }
        format.json { render json: @bear, status: :created, location: @bear }
      else
        format.html { render action: "new" }
        format.json { render json: @bear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bears/1
  # PUT /bears/1.json
  def update
    @bear = Bear.find(params[:id])

    respond_to do |format|
      if @bear.update_attributes(params[:bear])
        format.html { redirect_to @bear, notice: 'Bear was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bears/1
  # DELETE /bears/1.json
  def destroy
    @bear = Bear.find(params[:id])
    @bear.destroy

    respond_to do |format|
      format.html { redirect_to bears_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  #
  # Log user in & create a session
  # 
  def create
  	attempt_login
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
  def about
  end

  def home
  end

  def help
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find params[:id]
	end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
		#if save was successful::
  	if @user.save
      log_in @user
  		# render 'show'	#<< this would also display show user page, by running the show action above
      redirect_to @user, flash: { success: "User successfully created! Welcome #{@user[:name]}!" }
      # could also do it like this:
	  		# flash[:success] = "New user successfully created! Welcome #{@user[:name]}!"
	      # redirect_to @user
		#if save was unsuccessful::
  	else
  		flash[:danger] = "Failed to create new user, see error message"
  		render 'new'
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "Sample app"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

end

app/helpers/bears_helper.rb
module BearsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# logs out the current user
	def logout
		session.delete(:user_id)
		@current_user = nil
	end

  # Try to log in. User must have provided a password & email for this to work
	def attempt_login
  	get_login_attempt_content
  	if authentication_attempt == 'success'
			log_in
  	else
  		show_login_fail_msg
  	end
	end

	# get current user. Ensure db only gets hit 1X if current_user called more than 1X on a page
	def current_user
	  @current_user ||= User.where(id: session[:user_id]).first
	end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

	private

		def get_login_attempt_content
			@password, @email = 	params[:session][:password],
														params[:session][:email]
			@user_page = @user = 	(User.where email: @email).first
		end

		def authentication_attempt
			(@user && (@user.authenticate @password)) ? 'success' : 'fail'
		end

		def show_login_fail_msg
	  	flash.now[:danger] = 'Invalid email/password combo'
	  	render 'new'
		end
		
		# 
		# if authentication succeeds create a user session & redirect user to their profile (user) page
		# 
		def log_in
			# binding.pry
			session[:user_id] = @user.id   # this creates temporary cookies, which are encrypted
			redirect_to @user_page
		end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# returns image tag for Gravatar w/ a 'gravatar' CSS class & alt text == to user’s name
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/bears/_form.html.erb
<%= form_for(@bear) do |f| %>
  <% if @bear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bear.errors.count, "error") %> prohibited this bear from being saved:</h2>

      <ul>
      <% @bear.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :home %><br />
    <%= f.text_field :home %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bears/edit.html.erb
<h1>Editing bear</h1>

<%= render 'form' %>

<%= link_to 'Show', @bear %> |
<%= link_to 'Back', bears_path %>

app/views/bears/index.html.erb
<h1>Listing bears</h1>



<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Home</th>
    <th>Age</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bears.each do |bear| %>
  <tr>
    <td><%= bear.name %></td>
    <td><%= bear.type %></td>
    <td><%= bear.home %></td>
    <td><%= bear.age %></td>
    <td><%= bear.password_digest %></td>
    <td><%= link_to 'Show', bear %></td>
    <td><%= link_to 'Edit', edit_bear_path(bear) %></td>
    <td><%= link_to 'Destroy', bear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bear', new_bear_path %>

app/views/bears/new.html.erb
<h1>New bear</h1>

<%= render 'form' %>

<%= link_to 'Back', bears_path %>

app/views/bears/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bear.name %>
</p>

<p>
  <b>Type:</b>
  <%= @bear.type %>
</p>

<p>
  <b>Home:</b>
  <%= @bear.home %>
</p>

<p>
  <b>Age:</b>
  <%= @bear.age %>
</p>

<p>
  <b>Password digest:</b>
  <%= @bear.password_digest %>
</p>


<%= link_to 'Edit', edit_bear_path(@bear) %> |
<%= link_to 'Back', bears_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
          <li class="navbar-top"><div class="nav-link"><%= session ? User.where(session[:current_user_id])[0].name.capitalize : '' %></div></li>
        <% end %>

        <li class="navbar-top"><%= link_to "Help",   help_path, class: 'nav-link' %></li>
        <% if logged_in? %>

          <li class="navbar-top"><%= link_to "Users",    '#', class: 'nav-link' %></li>
          <li class="navbar-top"><%= link_to "Settings",    '#', class: 'nav-link'  %></li>
          <li class="navbar-top"><%= link_to "Profile", current_user, class: 'nav-link'  %></li>
          <li class="navbar-top"><%= link_to "Log out", logout_path, method: :delete, class: 'nav-link' %></li>
            <!-- This does the same thing as the link_to "Profile": -->
            <!-- <%= link_to "Profile", user_path(current_user) %> -->
        <% else %>
          <li class="navbar-top"><%= link_to "Log in", login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
	<!--[if lt IE 9]>
	  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!-- prevents cross-site request forgery -->
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <% flash_classes="alert alert-#{message_type}" %>
      <div class="<%= flash_classes %>" id="flash_msg">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <br><br>
  <%= debug(params) if Rails.env.development? %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<!-- associate the string "About" with the label :title - found in layouts/application.html.erb -->
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<!-- associate the string "Contact" with the label :title -->
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Home! You made it!</h1>

	  <h2>
	    This is the home page for the
	    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
	    sample application.
	  </h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary center" %>

</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>

app/views/users/create.html.erb
Test

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
		<%= form_for (@user) do |f| %>

			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name,												class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email,											class: 'form-control' %>

			<%= f.label :password,												"Password" %>
			<%= f.password_field :password, 							class: 'form-control' %>

			<%= f.label :password_confirmation,						"Confirmation" %>
			<%= f.password_field :password_confirmation, 	class: 'form-control' %>

			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="col-md-4">
		<h1 class="username">
			<%= gravatar_for @user %>
			<%= @user.name %>
		</h1>
	</aside>
</div>